version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-downloader-bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - downloads:/app/downloads
    healthcheck:
      test: ["CMD", "python", "-c", "import telegram; import yt_dlp"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

volumes:
  downloads:
    name: youtube-downloader-downloads
